<html>
  <head>
  </head>
  <body>
   <div class="col-lg-12 goes">
       <div class="goes-title">Goes16 - Satellite Infrared and Visible Images</div>
   </div>
<table>
  <tr>
    <td>
        <img src="https://services.meteored.com/img/sats/all/1-ar.jpg" width="600" height="500" title="Goes16-Argentina Infrarojo" alt="Goes16-Argentina Infrarojo">
    </td>
    <td>
        <img src="https://services.meteored.com/img/sats/all/2-ar.jpg" width="600" height="500" title="Goes16-Argentina Visible" alt="Goes16-Argentina Visible">
    </td>
  </tr>
</table>
  <a href="https://www.meteored.com.ar" target="_blank"><span class="goes-subtitle">Meteored.com.ar</span></a> - <a href="https://www.smn.gob.ar" target="_blank"><span class="goes-subtitle">SMN - Argentina</span></a>
  </body>
</html>
